server:
  port: 8080

# Eureka registration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


# this is for zipkin
management:
  tracing:
    sampling:
      probability: 1.0


    # this is oens all the api gatewayy for aps to connect
#  endpoints:
#    web:
#      exposure:
#        include: "*"
  # this is for the API gateway route  define which api goes where

spring:
  application:
    name: API-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: AUTHCLIENT
          uri: http://localhost:8081
          #     uri: lb://AUTHCLIENT
          predicates:
            - Path=/api/v1/client/**
#          filters:
#            - SetPath=/AUTHCLIENT/

        - id: UserInterface-gateway
          uri: http://localhost:8766
          #          uri: lb://UserInterface
          predicates:
            - Path=/api/v1/consumers/**
          filters:
            - SetPath=/api/v1/consumers/**

        - id: BarberDashboard
          uri: http://localhost:8767
          #          uri: lb://BarberDashboard
          predicates:
            - Path=/api/v1/services/**
          filters:
            - SetPath=/api/v1/services/**

        - id: notification-service
          uri: http://localhost:8040
          #          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
        - id: order-service
          uri: http://localhost:8070
          #          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
        - id: payment-service
          uri: http://localhost:8060
          #          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**


logging:
  level:
    root:
      root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO




        # this is use when configurer is used
        # https://medium.com/@ankithahjpgowda/api-gateway-in-spring-boot-3ea804003021#:~:text=API%20Gateway%20%E2%80%94%20receives%20incoming%20requests,that%20takes%20care%20of%20authentication
#spring:
#  application:
#    name: API-gateway
#  config:
#    import: "optional: configserver: http://localhost:8088"


# this is for mVC using in gateway https://docs.spring.io/spring-cloud-gateway/reference/spring-cloud-gateway-server-mvc/filters/tokenrelay.html

