server:
  port: 8070
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PostgresUrl:jdbc:postgresql://localhost:5432/barbershop}
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: ${Kafka_Url:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.orders.CustomerOrders.kafka.OrderConfirmation

application:
  config:
    customer-url: ${customerUrl:http://localhost:8766/api/v1/customers}  #providers services and notifications orders and payments
    payment-url: ${paymentUrl:http://localhost:8060/api/v1/payments}  # check ports
    servicesProvider-url: ${servicesProviderUrl:http://localhost:8767/api/v1/services}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EurekaUrl:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0
    # this is oens all the api gatewayy for aps to connect
  endpoints:
    web:
      exposure:
        include: "*"



