# the name of the service and the file name o  this congiguration should be the same

server:
  port: 8766

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discoveryServer:8761/eureka
#    registerWithEureka: true
#    fetchRegistry: true


management:
  tracing:
    sampling:
      probability: 1.0
    # this is oens all the api gatewayy for aps to connect
  endpoints:
    web:
      exposure:
        include: "*"


# PostgreSQL configuration.
spring:
  #  application:
  #    nameUser: UserInterface
  #    name: UserInterface
  datasource:
    url: jdbc:postgresql://postgres:5432/barbershop
    username: postgres
    password: password
  #addded
  jpa:
    generate-ddl: true
    database: postgresql


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri:  http://authserver:9000


