# the name of the service and the file name o  this congiguration should be the same

server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone:  ${EurekaUrl:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0
    # this is oens all the api gatewayy for aps to connect
  endpoints:
    web:
      exposure:
        include: "*"



# PostgreSQL configuration.
spring:
  application:
    nameUser: UserInterface
    name: UserInterface
  datasource:
    url: ${PostgresUrl:jdbc:postgresql://localhost:5432/barbershop}
    username: postgres
    password: password
  #addded
  jpa:
    generate-ddl: true
    database: postgresql

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SecurityIssuerUri:http://amberex-HP:9000}

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html